# Generated by Django 4.0.10 on 2023-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Name', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
